### ISSUE TITLE
map() Error

### ISSUE THREAD

**Issue by HamptonMakes** [ButterCMS/buttercms-ruby#19]
Unfortunately, it seems like in our haste to help, we actually made things worse! 

The older PR filtered the path name through `encode_www_form`, which is expecting a Hash object (like query params)... but the path is a string, so this errors. The test suite also doesn't currently pass on the main branch.

PR incoming!

(Also, let us know if you want help setting up ruby CI for this project... would help with the tests!)

```Failures:

  1) ButterCMS.request raises NotFound on 404
     Failure/Error:
       expect { ButterCMS.request("/posts/slug/") }
         .to raise_error(ButterCMS::NotFound)
     
       expected ButterCMS::NotFound, got #<NoMethodError: undefined method `map' for "/posts/slug/":String
       Did you mean?  tap> with backtrace:
         # ./lib/buttercms-ruby.rb:74:in `api_request'
         # ./lib/buttercms-ruby.rb:99:in `request'
         # ./spec/lib/butter-ruby_spec.rb:32:in `block (4 levels) in <top (required)>'
         # ./spec/lib/butter-ruby_spec.rb:32:in `block (3 levels) in <top (required)>'
         # /Users/hcatlin/.rvm/gems/ruby-2.7.2/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # ./spec/lib/butter-ruby_spec.rb:32:in `block (3 levels) in <top (required)>'
     # /Users/hcatlin/.rvm/gems/ruby-2.7.2/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  2) ButterCMS.request with an api token should make an api request
     Failure/Error: path = "#{@api_url.path}#{URI.encode_www_form(path)}?#{URI.encode_www_form(query)}"
     
     NoMethodError:
       undefined method `map' for "":String
       Did you mean?  tap
     # ./lib/buttercms-ruby.rb:74:in `api_request'
     # ./lib/buttercms-ruby.rb:99:in `request'
     # ./spec/lib/butter-ruby_spec.rb:14:in `block (4 levels) in <top (required)>'
     # /Users/hcatlin/.rvm/gems/ruby-2.7.2/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 0.02238 seconds (files took 0.17304 seconds to load)
14 examples, 2 failures
```

**Comment by HamptonMakes** [comment]
Now that I look at this... I don't even think we want THIS level of escapign either... as it encodes the `/` in the path.

I think the original intent here was to allow for some special characters to get escaped. I'm doing more research and will add to the test suite.

**Comment by HamptonMakes** [comment]
Ended up using a combination of the Pathname API and extending the test suite to deal with real life cases from @veuelive's codebase
